class Movie {
  final String title;
  final String description;
  final String posterUrl;
  final String releaseDate;
  final double rating;
  bool isBookmarked;
  final bool isFeatured;

  Movie({
    required this.title,
    required this.description,
    required this.posterUrl,
    required this.releaseDate,
    required this.rating,
    this.isBookmarked = false,
    this.isFeatured = false,
  });

  static List<Movie> staticMovies = [
    Movie(
      title: "The Shawshank Redemption",
      description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1994-09-23",
      rating: 9.3,
      isFeatured: true,
    ),
    Movie(
      title: "The Godfather",
      description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1972-03-24",
      rating: 9.2,
    ),
    Movie(
      title: "The Dark Knight",
      description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "2008-07-18",
      rating: 9.0,
      isFeatured: true,
    ),
    Movie(
      title: "Pulp Fiction",
      description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1994-10-14",
      rating: 8.9,
    ),
    Movie(
      title: "Forrest Gump",
      description: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1994-07-06",
      rating: 8.8,
      isBookmarked: true,
    ),
    Movie(
      title: "Inception",
      description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "2010-07-16",
      rating: 8.8,
      isFeatured: true,
    ),
    Movie(
      title: "The Matrix",
      description: "A computer programmer is led to fight an underground war against powerful computers who have constructed his entire reality with a system called the Matrix.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1999-03-31",
      rating: 8.7,
    ),
    Movie(
      title: "Goodfellas",
      description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1990-09-21",
      rating: 8.7,
    ),
    Movie(
      title: "The Lord of the Rings: The Return of the King",
      description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "2003-12-17",
      rating: 8.9,
      isFeatured: true,
    ),
    Movie(
      title: "Fight Club",
      description: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1999-10-15",
      rating: 8.8,
    ),
    Movie(
      title: "Star Wars: Episode V - The Empire Strikes Back",
      description: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1980-05-21",
      rating: 8.7,
      isBookmarked: true,
    ),
    Movie(
      title: "One Flew Over the Cuckoo's Nest",
      description: "A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1975-11-19",
      rating: 8.7,
    ),
    Movie(
      title: "Interstellar",
      description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "2014-11-07",
      rating: 8.6,
      isFeatured: true,
    ),
    Movie(
      title: "Casablanca",
      description: "A cynical American expatriate struggles to decide whether or not he should help his former lover and her fugitive husband escape French Morocco.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1942-11-26",
      rating: 8.5,
    ),
    Movie(
      title: "The Departed",
      description: "An undercover cop and a police informant play a cat and mouse game with each other as they attempt to find out each other's identity.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "2006-10-06",
      rating: 8.5,
    ),
    Movie(
      title: "Whiplash",
      description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "2014-10-10",
      rating: 8.5,
      isBookmarked: true,
    ),
    Movie(
      title: "The Prestige",
      description: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "2006-10-20",
      rating: 8.5,
    ),
    Movie(
      title: "Parasite",
      description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "2019-05-30",
      rating: 8.6,
      isFeatured: true,
    ),
    Movie(
      title: "The Green Mile",
      description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1999-12-10",
      rating: 8.6,
    ),
    Movie(
      title: "The Lion King",
      description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1994-06-24",
      rating: 8.5,
      isBookmarked: true,
    ),
    Movie(
      title: "Terminator 2: Judgment Day",
      description: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son John Connor from a more advanced and powerful cyborg.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1991-07-03",
      rating: 8.5,
    ),
    Movie(
      title: "Back to the Future",
      description: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1985-07-03",
      rating: 8.5,
      isFeatured: true,
    ),
    Movie(
      title: "Gladiator",
      description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "2000-05-05",
      rating: 8.5,
    ),
    Movie(
      title: "The Silence of the Lambs",
      description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1991-02-14",
      rating: 8.6,
    ),
    Movie(
      title: "Alien",
      description: "After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1979-05-25",
      rating: 8.4,
      isBookmarked: true,
    ),
    Movie(
      title: "Apocalypse Now",
      description: "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1979-08-15",
      rating: 8.4,
    ),
    Movie(
      title: "Saving Private Ryan",
      description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1998-07-24",
      rating: 8.6,
      isFeatured: true,
    ),
    Movie(
      title: "Spirited Away",
      description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "2001-07-20",
      rating: 8.6,
    ),
    Movie(
      title: "Psycho",
      description: "A Phoenix secretary embezzles money from her employer's client and encounters a young motel proprietor too long under the domination of his mother.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1960-06-16",
      rating: 8.5,
    ),
    Movie(
      title: "Rear Window",
      description: "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1954-08-01",
      rating: 8.4,
      isBookmarked: true,
    ),
    Movie(
      title: "City Lights",
      description: "With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl attempts to trick her into believing he is wealthy.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1931-01-30",
      rating: 8.5,
    ),
    Movie(
      title: "Modern Times",
      description: "The Tramp struggles to live in modern industrial society with the help of a young homeless woman.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1936-02-05",
      rating: 8.5,
    ),
    Movie(
      title: "Raiders of the Lost Ark",
      description: "In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's Nazis can obtain it.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1981-06-12",
      rating: 8.4,
      isFeatured: true,
    ),
    Movie(
      title: "Once Upon a Time in the West",
      description: "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1968-12-21",
      rating: 8.5,
    ),
    Movie(
      title: "The Usual Suspects",
      description: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1995-07-19",
      rating: 8.5,
    ),
    Movie(
      title: "Dr. Strangelove",
      description: "An insane general triggers a path to nuclear holocaust that a War Room full of politicians and generals frantically tries to stop.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1964-01-29",
      rating: 8.4,
      isBookmarked: true,
    ),
    Movie(
      title: "North by Northwest",
      description: "A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1959-07-01",
      rating: 8.3,
    ),
    Movie(
      title: "Vertigo",
      description: "A former police detective juggles wrestling with his personal demons and becoming obsessed with a beautiful woman.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1958-05-09",
      rating: 8.3,
    ),
    Movie(
      title: "Citizen Kane",
      description: "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance; 'Rosebud'.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1941-05-01",
      rating: 8.3,
      isFeatured: true,
    ),
    Movie(
      title: "Sunset Boulevard",
      description: "A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1950-08-10",
      rating: 8.4,
    ),
    Movie(
      title: "Lawrence of Arabia",
      description: "The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1962-12-11",
      rating: 8.3,
    ),
    Movie(
      title: "The Treasure of the Sierra Madre",
      description: "Fred Dobbs and Bob Curtin, both down on their luck in Tampico, Mexico in 1925, meet up with a grizzled prospector named Howard.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1948-01-24",
      rating: 8.2,
      isBookmarked: true,
    ),
    Movie(
      title: "Paths of Glory",
      description: "After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1957-10-25",
      rating: 8.4,
    ),
    Movie(
      title: "The Apartment",
      description: "A man tries to rise in his company by letting its executives use his apartment for trysts, but complications arise when he falls for one of their mistresses.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1960-06-15",
      rating: 8.3,
    ),
    Movie(
      title: "M",
      description: "When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1931-05-11",
      rating: 8.3,
      isFeatured: true,
    ),
    Movie(
      title: "Double Indemnity",
      description: "An insurance representative lets himself be talked by a seductive housewife into a murder/insurance fraud scheme that arouses the suspicion of his colleague.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1944-04-24",
      rating: 8.3,
    ),
    Movie(
      title: "Taxi Driver",
      description: "A mentally unstable veteran works as a night-time taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1976-02-09",
      rating: 8.3,
    ),
    Movie(
      title: "Singin' in the Rain",
      description: "A silent film production company and cast make a difficult transition to sound.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1952-04-11",
      rating: 8.3,
      isBookmarked: true,
    ),
    Movie(
      title: "Some Like It Hot",
      description: "After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.",
      posterUrl: "assets/images/Movie-1.png",
      releaseDate: "1959-03-29",
      rating: 8.2,
    ),
    Movie(
      title: "2001: A Space Odyssey",
      description: "After discovering a mysterious artifact buried beneath the Lunar surface, mankind is set on a course for a fateful encounter with an alien intelligence.",
      posterUrl: "assets/images/Movie-2.png",
      releaseDate: "1968-04-03",
      rating: 8.3,
      isFeatured: true,
    ),
  ];

  static List<Movie> getBookmarkedMovies() {
    return staticMovies.where((movie) => movie.isBookmarked).toList();
  }

}